=== leeoo/firefly/firefly-core/src/main/java/com/firefly/core/support/xml/beans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:bean="http://code.google.com/p/firefly/beans"
	targetNamespace="http://code.google.com/p/firefly/beans"
	elementFormDefault="qualified">

	<element name="value">
		<complexType mixed="true">
			<attribute name="type" />
		</complexType>
	</element>
	<element name="ref">
		<complexType>
			<attribute name="bean" />
		</complexType>
	</element>
	<element name="list">
		<complexType>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="bean:value"></element>
				<element ref="bean:ref"></element>
				<element ref="bean:list"></element>
			</choice>
			<attribute name="value-type" />
		</complexType>
	</element>
	<element name="map">
		<complexType>
			<sequence>
				<element name="entry" minOccurs="0" maxOccurs="unbounded">
					<complexType>
						<choice minOccurs="0" maxOccurs="unbounded">
							<element ref="bean:value"></element>
							<element ref="bean:ref"></element>
							<element ref="bean:map"></element>
						</choice>
						<attribute name="key" />
						<attribute name="value-type" />
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
	<element name="beans">
		<complexType>
			<sequence>
				<element name="bean" minOccurs="0" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="property" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<choice minOccurs="0" maxOccurs="1">
										<element ref="bean:ref"></element>
										<element ref="bean:value"></element>
										<element ref="bean:list"></element>
										<element ref="bean:map"></element>
									</choice>
									<attribute name="name" use="required" />
									<attribute name="value" />
									<attribute name="ref" />
								</complexType>
							</element>
						</sequence>
						<attribute name="id" />
						<attribute name="class" />
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== leeoo/firefly/firefly-core/src/test/resources/testImport.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://code.google.com/p/firefly/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://code.google.com/p/firefly/beans http://firefly.googlecode.com/files/beans.xsd">
	
	<import resource="testImport1.xml"/>
	
	<bean id="person" class="test.component3.Person">
		<property name="name" value="Jack"/>
		<property name="age" value="12"/>
	</bean>
	<bean id="person2" class="test.component3.Person">
		<property name="name">
			<value>Bob</value>
		</property>
		<property name="age" value="32"/>
	</bean>

</beans>

=== leeoo/firefly/firefly-core/src/test/resources/firefly.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://code.google.com/p/firefly/beans" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://code.google.com/p/firefly/beans http://firefly.googlecode.com/files/beans.xsd">
		
	<bean id="person" class="test.component3.Person">
		<property name="name" value="Jack"/>
		<property name="age" value="12"/>
	</bean>
	<bean id="person2" class="test.component3.Person">
		<property name="name" value="Bob"/>
		<property name="age" value="32"/>
	</bean>
	<bean id="personService" class="test.component3.PersonService">
		<property name="person" ref="person"/>
		<property name="testList">
			<list>
				<value type="int">123</value>
				<ref bean="person2"/>
				<value type="java.lang.String">dfdf</value>
				<ref bean="person"/>
				
			</list>
		</property>
	</bean>
</beans>

=== leeoo/firefly/firefly-demo1/src/main/resources/firefly.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://code.google.com/p/firefly/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://code.google.com/p/firefly/beans http://firefly.googlecode.com/files/beans.xsd">

	<component-scan base-package="com.firefly.demo1"/>
	<mvc view-path="/WEB-INF/page" view-encoding="UTF-8" view-type="fft"/>

	<!-- Datasource -->
	<bean id="dataSource" class="com.jolbox.bonecp.BoneCPDataSource">
		<property name="driverClass" value="${jdbc.driverClassName}" />
		<property name="jdbcUrl" value="${jdbc.url}" />
		<property name="username" value="${jdbc.username}" />
		<property name="password" value="${jdbc.password}" />
		<property name="idleConnectionTestPeriod" value="60" />
		<property name="idleMaxAge" value="240" />
		<property name="maxConnectionsPerPartition" value="30" />
		<property name="minConnectionsPerPartition" value="10" />
		<property name="partitionCount" value="3" />
		<property name="acquireIncrement" value="5" />
		<property name="statementsCacheSize" value="100" />
		<property name="releaseHelperThreads" value="3" />
	</bean>
</beans>
